defaults
auth           on
tls            on
tls_starttls   on
account        mailjet
host           in-v3.mailjet.com
port           587
from           noreplay@nubons.com
user           $SMTP_USERNAME
password       $SMTP_PASSWORD
logfile        /var/log/msmtp.log
syslog         on
